version: 2

models:
  - name: customers
    description: Customer attributes plus first order date and total orders count
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_order_at
        description: date (UTC) of first order
      - name: number_of_orders
        description: total order count
  
  - name: new_weekly_customers
    description: '{{ doc("new_weekly_customers") }}'  # <- needs to be doc() not docs()
    columns:
      - name: signup_week
        description: a truncated date (Monday)
        tests:
          - unique
          - not_null